config/routes.rb
Todo::Application.routes.draw do
  resources :lists

  root 'static#index'

  get "/auth/twitter/callback" => "twitter#callback"
  get "/signout" => "twitter#signout", :as => :signout

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :lists
  # Public: Find or create user with omniauth attributes.
  #
  # omniauth - Omniauth Hash.
  #
  # Returns a User.
  def self.from_omniauth(omniauth)
    where(:uid => omniauth["uid"]).first || create_from_omniauth(omniauth)
  end

  # Internal: Create user from omniauth attributes.
  #
  # omniauth - Omniauth Hash.
  #
  # Returns a User.
  def self.create_from_omniauth(omniauth)
    create! do |user|
      user.uid      = omniauth["uid"]
      user.username = omniauth["info"]["nickname"]
      user.token    = omniauth["credentials"]["token"]
      user.secret   = omniauth["credentials"]["secret"]
    end
  end

  # Public: Twitter username.
  # column :username
  # Returns a String.
  validates :username, :presence => true

  # Public: Twitter uid.
  # column :uid
  # Returns a String.
  validates :uid, :presence => true

  # Public: Twitter access token.
  # column :token
  # Returns a String.
  validates :token, :presence => true

  # Public: Twitter access secret.
  # column :secret
  # Returns a String.
  validates :secret, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  # Public: Is the user signed in?
  #
  # Returns a TrueClass or FalseClass.
  def signed_in?
   !!current_user
  end
  helper_method :signed_in?

  # Internal: Set the currently logged in user for request and session.
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  # Internal: Set the currently logged in user for request and session.
  def current_user=(user)
    if user.present?
      set_current_user_for_request_and_session(user)
    else
      clear_current_user_for_request_and_session
    end
  end

  # Internal: Set the currently logged in user for request and session.
  def set_current_user_for_request_and_session(user)
    @current_user = user
    session[:user_id] = user.id
  end

  # Internal Clear the current user for request and session.
  def clear_current_user_for_request_and_session
    @current_user = nil
    session[:user_id] = nil
  end

  # Internal: The omniauth hash from the request env.
  #
  # Returns a Hash.
  def omniauth
    request.env['omniauth.auth']
  end

  # Internal: Require the user to be signed in.
  def signin_required
    return if signed_in?
    session[:return_to] = request.path if request.path
    redirect_to "/auth/twitter"
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :signin_required
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
  #  @lists = List.all
    @lists = List.where(:user_id => current_user.id)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new do |list|
      list.name = params[:list][:name]
      list.description = params[:list][:description]
      list.user_id = current_user.id
    end

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    list = List.find(params[:id])
    list.name = params[:list][:name]
    list.description = params[:list][:description]

    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :discription, :status)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController

  def callback
    user = User.from_omniauth(omniauth)
    self.current_user = user

    redirect_to session[:return_to] || lists_path
  end

  # Public: Signs user out of todo.
  def signout
    self.current_user = nil

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="box">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div class="top">
  <%= link_to 'Show', @list, :class => "button" %>
  <%= link_to 'Back', lists_path, :class => "button" %>
  <h1>Editing list</h1>
</div>

<%= render 'form' %>

app/views/lists/index.html.erb
<div class="top">
  <%= link_to 'New List', new_list_path, :class => "button" %>
  <h1>welcome!</h1>
  <div class="user_name">
    <% if current_user %>
      <p><%= current_user.username %></p>
      <%= link_to "Sign out", signout_path, :class => "button", :style => "float:right;" %>
    <% else %>
      <%= link_to "Sign in", "/auth/twitter", :class => "button" %>
    <% end %>
  </div>
</div>

<div class="box" style="width:90%;">
  <h1>Listing lists</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @lists.each do |list| %>
        <tr>
          <td><%= list.name %></td>
          <td><%= list.description %></td>
          <td><%= link_to 'Show', list, :class => "button" %></td>
          <td><%= link_to 'Edit', edit_list_path(list), :class => "button" %></td>
          <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/lists/new.html.erb
<div class="top">
  <%= link_to 'Back', lists_path, :class => "button" %>
  <h1>Create a New list</h1>
</div>
<%= render 'form' %>

app/views/lists/show.html.erb
<div class="top">
  <%= link_to 'Back', lists_path, :class => "button" %>
  <%= link_to 'Edit', edit_list_path(@list), :class => "button" %>
  <h1>show the list</h1>
</div>
<p id="notice"><%= notice %></p>

<div class="box">
  <div class="field">
    <p><span class="hh1">Name:</span> <%= @list.name %></p>
  </div class="field">
  <div class="field">
    <p><span class="hh1">Description:</span> <%= @list.description %></p>
  </div class="field">
</div class="box">

app/views/twitter/callback.html.erb
callback!